require('mappings')
require('options')
require('plugins')
require('core.treesitter-nvim')
require('core.lualine-nvim')
require('core.bufferline-nvim')
require('core.nvimtree-nvim')
require('core.telescope-nvim')
require('core.cmp-nvim')
require('core.dashboard-nvim')
require('core.lspconfig-nvim')
require('core.gitsign-nvim')
require('core.autopairs-nvim')
require('core.signature-nvim')
require('core.indentline-nvim')
vim.opt.fillchars = {eob = " "}
