local opt = {}
vim.g.mapleader = " "
local map = vim.api.nvim_set_keymap


map("n", "gD", "<Cmd>lua vim.lsp.buf.declaration()<CR>", opt)
map("n", "gd", "<Cmd>lua vim.lsp.buf.definition()<CR>", opt)
map("n", "K", "<Cmd>lua vim.lsp.buf.hover()<CR>", opt)
map("n", "gi", "<cmd>lua vim.lsp.buf.implementation()<CR>", opt)
map("n", "<C-k>", "<cmd>lua vim.lsp.buf.signature_help()<CR>", opt)
map("n", "<space>wa", "<cmd>lua vim.lsp.buf.add_workspace_folder()<CR>", opt)
map("n", "<space>wr", "<cmd>lua vim.lsp.buf.remove_workspace_folder()<CR>", opt)
map("n", "<space>wl", "<cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<CR>", opt)
map("n", "<space>D", "<cmd>lua vim.lsp.buf.type_definition()<CR>", opt)
map("n", "<space>rn", "<cmd>lua vim.lsp.buf.rename()<CR>", opt)
map("n", "gr", "<cmd>lua vim.lsp.buf.references()<CR>", opt)
map("n", "<space>e", "<cmd>lua vim.lsp.diagnostic.show_line_diagnostics()<CR>", opt)
map("n", "[d", "<cmd>lua vim.lsp.diagnostic.goto_prev()<CR>", opt)
map("n", "]d", "<cmd>lua vim.lsp.diagnostic.goto_next()<CR>", opt)
map("n", "<space>q", "<cmd>lua vim.lsp.diagnostic.set_loclist()<CR>", opt)
map('i', 'jk', '<esc>', opt)
map('n', '<Leader>h', '<C-w>h', opt)
map('n', '<Leader>j', '<C-w>j', opt)
map('n', '<Leader>k', '<C-w>k', opt)
map('n', '<Leader>l', '<C-w>l', opt)
map('n', '<Leader>o', ':BufferLineCyclePrev<CR>', opt)
map('n', '<Leader>p', ':BufferLineCycleNext<CR>', opt)
map('n', '<Leader>v', ':vs<CR>', opt)
map('n', '<Leader>b', ':sp<CR>', opt)
map('n', '<C-c>', ':bd<CR>', opt)
map('n', '<Leader>e', ':NvimTreeToggle<CR>', opt)
map('n', '<Leader>z', '<cmd>nohlsearch<CR>', opt)
map("n", "<leader>ff", "<cmd>lua vim.lsp.buf.formatting()<CR>", opt)
map('n', '<Leader>w', ':w<CR>', opt)
map('n', '<Leader>ww', ':SudaWrite<CR>', opt)
map('n', '<Leader>q', ':q<CR>', opt)
map('n', '<Leader>qq', ':q!<CR>', opt)
map("n", ";", ":", opt)
map("n", "<leader>.", "<cmd>Telescope find_files<CR>", opt)
map("n", "<leader>fe", "<cmd>Telescope current_buffer_fuzzy_find<CR>", opt)
map("n", "<leader>:", "<cmd>Telescope commands<CR>", opt)
map("n", "<leader>bb", "<cmd>Telescope buffers<CR>", opt)
map("n", "<leader>aa", ":Telescope git_branches<CR>", opt)
map("n", "<leader>ss", ":Telescope git_commits<CR>", opt)
map("n", "<leader>pi", ":PackerInstall<CR>", opt)
map("n", "<leader>ps", ":PackerSync<CR>", opt)
map("n", "<leader>td", ":lua package.loaded.presence:update()<CR>", opt)
map("n", "<C-x>", ":10new +terminal | setlocal nobuflisted <CR>", opt) --  term bottom
map("t", "jk", "<C-\\><C-n>", opt)
map("i", "<F2>", "<Esc>:FloatermToggle<CR>", opt)
map("n", "<F2>", "<C-\\><C-n>:FloatermToggle<CR>", opt)
map("n", "tZ", ":FloatermUpdate --width=0.8 --height=0.8<CR>", opt)
map("n", "tz", ":FloatermUpdate --width=1.0 --height=1.0<CR>", opt)
map("n", "<leader>zz", ":ZenMode<CR>", opt)
map("n", "<A-h>", "<ESC>:<<<CR>", opt)
map("n", "<A-j>", "<ESC>:m. +1<CR>", opt)
map("n", "<A-k>", "<ESC>:m. -2<CR>", opt)
map("n", "<A-l>", "<ESC>:>><CR>", opt)
vim.g.onedark_toggle_style_keymap = '<Leader>tc'
